root = "."
testdata_dir = ".air/testdata"
tmp_dir = ".air"

[build]
  args_bin = []
  bin = "./.air/main"
  cmd = "go build -o ./.air/main ."
  delay = 0
  exclude_dir = [".air", "vendor", "dist"]
  exclude_file = ["makefile"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["src"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = ".air/build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
